#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

require_once __DIR__.'/app/Support/polyfills.php';

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);
